name: Deploy to Heroku

on:
  push:
    branches:
      - master

jobs:
  deploy:
    if: ${{ contains(toJson(github.event.commits.*.message), '#deploy') }}
    runs-on: ubuntu-latest
    steps:
      - name: Check files
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '16.14.2'
      - name: Build the client
        run: |
          cd client
          npm ci
          npm run build
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          appdir: 'server'
          healthcheck: 'https://norway-sushibar-online-order.herokuapp.com/health'
          checkstring: 'ok'
          delay: 5
          rollbackonhealthcheckfailed: true